# Generated by Django 2.0.1 on 2018-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitoex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField(null=True, verbose_name='bitoex_buy')),
                ('sell', models.IntegerField(null=True, verbose_name='bitoex_sell')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='bitoex_ts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitoex',
                'verbose_name_plural': 'Bitoexs',
                'ordering': ['-created_at'],
            },
        ),
    ]
